// import globals.css
import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css"
import { SidebarNav } from "@/components/sidebar-nav"
import { MobileNav } from "@/components/mobile-nav"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            >
               <header className="sticky top-0 z-40 border-b bg-background md:hidden">
                <div className="container flex h-16 items-center justify-between ">
                  <MobileNav />
                </div>
              </header>
              <SidebarNav />
              {children}
              </ThemeProvider></body>
    </html>
  )
}
